version: "2.1"
orbs:
  codecov: codecov/codecov@4.1.0
  node: circleci/node@4.7.0
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run:
          name: install jest library
          command: npm install jest
      - run:
          name: unit testing
          command: npm run test -- --coverage
      - codecov/upload

workflows:
  test_my_app:
    jobs:
      - build
      - test
