version: "2.1"
orbs:
  node: circleci/node@x.y
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run:
          name: install jest library
          command: npm install jest
      - run:
          name: install jest library
          command: npm install jest
      - run:
          name: unit testing
          command: npm run test -- --coverage

      - codecov/upload

workflows:
  test_my_app:
    jobs:
      - test
